config/routes.rb
Rails.application.routes.draw do
  
  root "home#top"
  get 'ownersinfo/:id/home' => "ownersinfo#home"
  get "ownersinfo/new" => "ownersinfo#new"
  get "ownersinfo/:id/edit" => "ownersinfo#edit"
  post "ownersinfo/:id/update" => "ownersinfo#update"
  post "ownersinfo/:id/reset_image" => "ownersinfo#reset_image"
  get "home/top" => "home#top"
  get "home/search" => "home#search"
  get "home/keyword_search" => "home#keyword_search"

  devise_for :owners, controllers: {
    sessions:      'owners/sessions',
    passwords:     'owners/passwords',
    registrations: 'owners/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def search
  end

  def keyword_search
    @ownersinfo = Ownerinfo.all

    @ownersinfo = @ownersinfo.where('store_name LIKE ?', "%#{params[:search]}%") if params[:search].present?
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/keyword_search.html.erb
<!-- 検索結果一覧の表示 -->
<% @ownersinfo.each do |ownersinfo| %>
  <p><%= ownersinfo.store_name %></p>
<% end %>
<!-- 検索結果がない場合 -->
<% if @ownersinfo.size == 0 %>
 <p>検索結果がありませんでした</p>
<% end %>

app/views/home/search.html.erb
<p>現在地から検索（googlemap導入後作成）</p>
<p>都道府県から検索（プルダウンできるようにする）</p>

<%= form_with url: home_keyword_search_path, method: :get, local: true do |form| %>
  キーワードから検索<%= form.text_field :search %>
  <%= form.submit 'Search', name: nil %>
<% end %>

app/views/home/top.html.erb
<h1>ポートフォリオ</h1>