config/routes.rb
Rails.application.routes.draw do
  
  root "home#top"
  get 'ownersinfo/:id/home' => "ownersinfo#home"
  get "ownersinfo/new" => "ownersinfo#new"
  get "ownersinfo/:id/edit" => "ownersinfo#edit"
  post "ownersinfo/:id/update" => "ownersinfo#update"
  post "ownersinfo/:id/reset_image" => "ownersinfo#reset_image"
  get "home/top" => "home#top"
  get "home/search" => "home#search"
  get "home/keyword_search" => "home#keyword_search"

  devise_for :owners, controllers: {
    sessions:      'owners/sessions',
    passwords:     'owners/passwords',
    registrations: 'owners/registrations'
  }
  devise_for :users, controllers: {
    sessions:      'users/sessions',
    passwords:     'users/passwords',
    registrations: 'users/registrations'
  }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PortfolioMock</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  　<header>
      <li>
      <%= link_to "ボードゲームカフェの検索", "/home/search" %> <!-- 検索画面に移行する -->
      </li>
      <li>
        <%= link_to "ログイン", new_user_session_path, class: 'post' %> <!-- ログイン画面に移行する -->
      </li>
      <li>
        <%= link_to "新規登録", new_user_registration_path, class: 'post' %> <!-- 新規登録画面に移行する -->
      </li>
      <li>
        （オーナー、店舗の方は<%= link_to "こちら", new_owner_registration_path, class: 'post' %>） <!-- オーナーの新規登録画面に移行する -->
      </li>
      <%= link_to "ログアウト", destroy_owner_session_path, method: :delete %>
      
  　　</header>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>

    <footer>
    <li>
      <%= link_to "トップ", "/home/top" %> <!-- トップ画面に移行する -->
    </li>
    <li>
      お問い合わせ
    </li>
    </footer>
  </body>
</html>